version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:15.6.7-ce.0'
    restart: always
    hostname: '172.18.176.1'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.18.176.1'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['initial_root_password'] = 'adminadmin'
    ports:
      - '9080:80'
      - '9443:443'
      - '9022:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'